name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'update readme'
        run: |
          echo "helloworld" > readme.md
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: list files
        run: |
          URL="https://google.com/"
            HTTP_RESPONSE=$(curl --silent -O dev/null --write-out "%{http_code}" -X GET https://google.com/)
          echo "$HTTP_RESPONSE"
      # - name: 'Create .npmrc'
      #   id: create_npmrc
      #   shell: bash
      #   run: |
      #     npm config set registry https://mbtech.jfrog.io/artifactory/async-virtual/
      #     curl -s -u balaji.m89@gmail.com:${{secrets.token_val}} https://mbtech.jfrog.io/artifactory/api/npm/auth/ > .npmrc
      #     echo -e "strict-ssl=false\n registry=https://mbtech.jfrog.io/artifactory/async-virtual/" >> .npmrc
      # - name: File exists
      #   if: steps.create_npmrc.outputs.files_exists == 'true'
      #   run: |
      #    echo "It exists !"
      # - run: |
      #     npm config fix
      #     cat .npmrc
      # - run: npm install
      # - run: npm publish --registry https://mbtech.jfrog.io/artifactory/async-virtual/
