name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: 'Create .npmrc'
        id: create_npmrc
        shell: bash
        run: |
          npm config set registry https://mbtech.jfrog.io/artifactory/async-virtual/
          curl -s -u balaji.m89@gmail.com:AKCp8oi7tkEU36vY9p26e8dJHVwWTkFQ5jGyqASAejmkxZBaqPHH1bm95dJpY5b3QrYNVoqkt https://mbtech.jfrog.io/artifactory/api/npm/auth/ > .npmrc
      - name: File exists
        if: steps.create_npmrc.outputs.files_exists == 'true'
        run: |
         echo "It exists !"
      - run: |
          npm config fix
          cat .npmrc
      - run: npm install
      - run: npm publish --registry https://mbtech.jfrog.io/artifactory/async-virtual/
