name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'update readme'
        run: |
          echo "helloworld" > readme.md
      - name: 'json merge'
        run: |
          json_data='{
            "email": "test",
            "alerts": ["alert1", "alert2"]
          }'
          
          # Use jq to parse and assign the JSON to a variable
          email=$(echo "$json_data" | jq -r '.email')
          alerts=($(echo "$json_data" | jq -r '.alerts[]'))
          
          # Print the values to verify
          echo "Email: $email"
          echo "Alerts: ${alerts[@]}"
      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18.x'
      # - name: list files
      #   run: |
      #     URL="https://google.com/"
      #       HTTP_RESPONSE=$(curl --silent -o /dev/null -w "%{http_code}" -X GET https://google.com/)
      #     echo "$HTTP_RESPONSE"
      #     if [ "$HTTP_RESPONSE" = "200" ]; then
      #     echo "success"
      #     else
      #     echo "failure"
      #     fi
      # - name: 'Create .npmrc'
      #   id: create_npmrc
      #   shell: bash
      #   run: |
      #     npm config set registry https://mbtech.jfrog.io/artifactory/async-virtual/
      #     curl -s -u balaji.m89@gmail.com:${{secrets.token_val}} https://mbtech.jfrog.io/artifactory/api/npm/auth/ > .npmrc
      #     echo -e "strict-ssl=false\n registry=https://mbtech.jfrog.io/artifactory/async-virtual/" >> .npmrc
      # - name: File exists
      #   if: steps.create_npmrc.outputs.files_exists == 'true'
      #   run: |
      #    echo "It exists !"
      # - run: |
      #     npm config fix
      #     cat .npmrc
      # - run: npm install
      # - run: npm publish --registry https://mbtech.jfrog.io/artifactory/async-virtual/
